const { Worker } = require('worker_threads')

const fs = require("fs")
const buffer = fs.readFileSync(__dirname + "/snapshot.jpg")

const worker = new Worker(__dirname + `/worker.mjs`, {workerData: "1"})
const worker2 = new Worker(__dirname + `/worker.mjs`, {workerData: "2"})
const worker3 = new Worker(__dirname + `/worker.mjs`, {workerData: "3"})
const worker4 = new Worker(__dirname + `/worker.mjs`, {workerData: "4"})
const worker5 = new Worker(__dirname + `/worker.mjs`, {workerData: "5"})
const worker6 = new Worker(__dirname + `/worker.mjs`, {workerData: "6"})
const worker7 = new Worker(__dirname + `/worker.mjs`, {workerData: "7"})
const worker8 = new Worker(__dirname + `/worker.mjs`, {workerData: "8"})

worker.on('message', message => {console.log(message)})
worker2.on('message', message => {console.log(message)})
worker3.on('message', message => { console.log(message)})
worker4.on('message', message => { console.log(message)})
worker5.on('message', message => {console.log(message)})
worker6.on('message', message => {console.log(message)})
worker7.on('message', message => { console.log(message)})
worker8.on('message', message => { console.log(message)})

worker.postMessage(buffer)
worker2.postMessage(buffer)
worker3.postMessage(buffer)
worker4.postMessage(buffer)
worker5.postMessage(buffer)
worker6.postMessage(buffer)
worker7.postMessage(buffer)
worker8.postMessage(buffer)



// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 2000)
// setTimeout(() => worker.postMessage(buffer), 3000)
// setTimeout(() => worker.postMessage(buffer), 4000)
// setTimeout(() => worker.postMessage(buffer), 5000)
// setTimeout(() => worker.postMessage(buffer), 6000)
// setTimeout(() => worker.postMessage(buffer), 7000)

// setTimeout(() => worker2.postMessage(buffer), 1000)
// setTimeout(() => worker2.postMessage(buffer), 2000)
// setTimeout(() => worker2.postMessage(buffer), 3000)
// setTimeout(() => worker2.postMessage(buffer), 4000)
// setTimeout(() => worker2.postMessage(buffer), 5000)
// setTimeout(() => worker2.postMessage(buffer), 6000)
// setTimeout(() => worker2.postMessage(buffer), 7000)

// setTimeout(() => worker3.postMessage(buffer), 1000)
// setTimeout(() => worker3.postMessage(buffer), 2000)
// setTimeout(() => worker3.postMessage(buffer), 3000)
// setTimeout(() => worker3.postMessage(buffer), 4000)
// setTimeout(() => worker3.postMessage(buffer), 5000)
// setTimeout(() => worker3.postMessage(buffer), 6000)
// setTimeout(() => worker3.postMessage(buffer), 7000)


setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)
setTimeout(() => worker.postMessage(buffer), 1000)

setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)
setTimeout(() => worker2.postMessage(buffer), 1000)

setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)
setTimeout(() => worker3.postMessage(buffer), 1000)

setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)
setTimeout(() => worker4.postMessage(buffer), 1000)

// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)
// setTimeout(() => worker5.postMessage(buffer), 1000)

// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)
// setTimeout(() => worker6.postMessage(buffer), 1000)

// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)
// setTimeout(() => worker7.postMessage(buffer), 1000)

// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)
// setTimeout(() => worker8.postMessage(buffer), 1000)



// ------

// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
// setTimeout(() => worker.postMessage(buffer), 1000)
